command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
port: 8000
environment_variables:
  PYTHONPATH: "."
  DATABRICKS_HOST: "${DATABRICKS_HOST}"
  DATABRICKS_TOKEN: "${DATABRICKS_TOKEN}"
  DATABRICKS_HTTP_PATH: "${DATABRICKS_HTTP_PATH}"
  LLM_AGENT_ENDPOINT: "${LLM_AGENT_ENDPOINT}"
