command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
port: 8000
environment_variables:
  PYTHONPATH: "."
  DATABRICKS_HOST: "https://fe-vm-hls-amer.cloud.databricks.com"
  DATABRICKS_HTTP_PATH: "/sql/1.0/warehouses/4b28691c780d9875"
